# Generated by Django 4.2.5 on 2024-03-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_name_project_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='users_id',
        ),
    ]
