# Generated by Django 4.2.5 on 2024-03-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_users_project_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users_id',
            new_name='users',
        ),
    ]
